### ISSUE TITLE
make all_ql_tests fails

### ISSUE THREAD

**Issue by Thirsty2** [QuickLogic-Corp/quicklogic-fpga-toolchain#33]
It fails differently than it used to:

[ 12%] Generating btn_counter-ql-jimbob4/ql-s3-ql-pp3e-virt-ql-pp3e-wlcsp/top.bit
Traceback (most recent call last):
  File "/symbiflow-arch-defs/build/env/conda/bin/qlfasm", line 11, in <module>
    load_entry_point('quicklogic-fasm', 'console_scripts', 'qlfasm')()
  File "/symbiflow-arch-defs/quicklogic/common/utils/quicklogic-fasm/quicklogic_fasm/qlfasm.py", line 290, in main
    assembler.parse_fasm_filename(args.infile)
  File "/symbiflow-arch-defs/quicklogic/common/utils/fasm-utils/fasm_utils/fasm_assembler.py", line 169, in parse_fasm_filename
    self.process_fasm_line(line, missing_features)
  File "/symbiflow-arch-defs/quicklogic/common/utils/fasm-utils/fasm_utils/fasm_assembler.py", line 161, in process_fasm_line
    'for the feature: {}'.format(str(fasmline.set_feature.feature))
fasm_utils.fasm_assembler.FasmInconsistentBits: The implementation of enable_feature() function did not use the set_config_bit() or clear_config_bit() for the feature: X16Y18.GMUX.GMUX.I_invblock.I_J0.ZINV.IS0
make[3]: *** [quicklogic/pp3/tests/btn_counter/CMakeFiles/btn_counter-ql-jimbob4_openocd.dir/build.make:78: quicklogic/pp3/tests/btn_counter/btn_counter-ql-jimbob4/ql-s3-ql-pp3e-virt-ql-pp3e-wlcsp/top.bit] Error 1
make[2]: *** [CMakeFiles/Makefile2:281410: quicklogic/pp3/tests/btn_counter/CMakeFiles/btn_counter-ql-jimbob4_openocd.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:271186: quicklogic/pp3/tests/CMakeFiles/all_ql_tests.dir/rule] Error 2
make: *** [Makefile:188: quicklogic/pp3/tests/CMakeFiles/all_ql_tests.dir/rule] Error 2
The command '/bin/sh -c make all_ql_tests' returned a non-zero code: 2

**Comment by Thirsty2** [comment]
It built fine when I tested this last night, and make all_ql_tests passed with no errors, so I am closing this.
